version: "3.7"

services:
    # image project
    web-app:
        platform: "linux/amd64"
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "5173:80"
            - "9000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    # db mysql
    db:
        platform: "linux/amd64"
        image: mysql:5.7.34
        restart: unless-stopped
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3383:3306"
        networks:
            - laravel
        environment:
            MYSQL_ROOT_PASSWORD: admi123
            MYSQL_DATABASE: laravel-db
            MYSQL_USER: some
            MYSQL_PASSWORD: root
    # redis
    redis:
        image: redis:latest
        networks:
            - laravel

networks:
    laravel:
        driver: bridge